# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            R4Dat
tagline:          'A brief description'
description:      'Personal thoughts on <a href="https://www.informs.org/About-INFORMS/What-is-Operations-Research" target="_blank">Operations Research</a>, Statistics, and Analytics.'
url:              https://github.com/r4dat
baseurl:          /

author:
  name:           'Rob R'
  url:            https://github.com/r4dat

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
