# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            R4Dat
tagline:          'A brief description'
description:      'Personal thoughts on Operations Research, Analytics, and Life.'
url:              https://github.com/r4dat
baseurl:          /

author:
  name:           'Rob R'
  url:            https://github.com/r4dat

paginate:         5

gems:
  - jekyll-sitemap

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
